name: Report

on:
  push:

jobs:
  report:
    runs-on: ubuntu-latest
    container: aiplan4eu/unified-planning

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Checkout the Unified Planning Framework
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/unified-planning
          path: unified-planning

      - name: Install Unified-Planning
        run: python3 -m pip install unified-planning/

      - name: Install tamer
        run: python3 -m pip install up-tamer --pre

      - name: Install Aries (dev-build)
        run: python3 -m pip install https://github.com/plaans/aries/releases/download/latest/up_aries.tar.gz

      - name: Report validation
        run: python3 report.py --mode plan-validation

      - name: Report
        run: 'python3 report.py aries tamer --mode oneshot --prefix up:'

      - name: Install FMAP
        run: python3 -m pip install up-fmap/
